# Generated by Django 2.2.7 on 2019-11-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('course_number', models.IntegerField()),
                ('group_number', models.IntegerField()),
                ('teacher', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.IntegerField()),
                ('first_day', models.CharField(max_length=10)),
                ('end_day', models.CharField(max_length=10)),
            ],
        ),
    ]
