# Generated by Django 2.2.7 on 2019-11-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_day',
            field=models.IntegerField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='first_day',
            field=models.IntegerField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه')]),
        ),
    ]
