# Generated by Django 2.2.7 on 2019-11-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edusys', '0006_auto_20191108_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='end_day',
            new_name='second_day',
        ),
    ]
