# Generated by Django 2.2.7 on 2019-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusys', '0007_auto_20191108_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_date',
            field=models.DateField(default='2000-1-1'),
            preserve_default=False,
        ),
    ]
