# Generated by Django 2.2.7 on 2019-11-08 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edusys', '0008_course_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_date',
            field=models.DateField(default='2000-1-1'),
        ),
    ]
