# Generated by Django 2.2.7 on 2019-11-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusys', '0008_course_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_date',
            field=models.DateField(default='2000-1-1'),
        ),
    ]
